services:
  - type: web
    name: techgyant-insights-api
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: python simple_setup.py && uvicorn api.main_simple:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
